name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Configuração do Java
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      # Instalação do navegador (Chrome)
      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      # Configuração do display virtual para Selenium
      - name: Set up display
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1920x1080x16 &

      # Build e execução dos testes com Maven
      - name: Build and Test with Maven
        run: |
          mvn clean install
          mvn test
